### ISSUE TITLE
Duda en la creación de Schema de MongoDB

### ISSUE THREAD

**Issue by aglezg** [ULL-ESIT-INF-DSI-2122/ull-esit-inf-dsi-21-22-prct12-music-api-grupo_h#1]
https://github.com/ULL-ESIT-INF-DSI-2122/ull-esit-inf-dsi-21-22-prct12-music-api-grupo_h/blob/3ea67bdfbfeca916afc300f77ff9685ac62453f2/src/songs/song.ts#L35-L41

Buenas tardes, @esegredo 
A la hora de realizar el esquema propio de las canciones para incluirlo en la base de datos propia de Mongo nos preguntábamos si habría alguna manera de simplificar el código propio del atributo `enum`, en donde no hiciera falta reescribir todos los valores posibles que puede tener un género. Pues estos los tenemos ya tipados a través de un alias de tipo.

```
export type Genre = 'Rock' | 'Heavy Metal' | 'Reggaeton' | 'Jazz' | 'Pop' | 'Rap' |
  'Hip-hop' | 'Trap' | 'Urban' | 'Latino' | 'Bachata' | 'Music alternative' | 'Electro';
```

@AnaVGD @alu0101365107 @Jacobsrguez

**Comment by esegredo** [comment]
Hola, buenas tardes.

Quizás podría hacerse a través de un validador, en lugar de un enum, donde comprueben si el valor concreto está dentro de un array o conjunto, y en caso de que no esté, no permitir almacenar el documento.

Ya me dicen si lo consiguen hacer así.

Saludos.
